name: Check TikTok Live

on:
  push:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-live:
    runs-on: ubuntu-latest

    concurrency:
      group: tiktok-live-job
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: serverless-deploy

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Run TikTok Live Job
        run: node src/job.js
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}